# Generated by Django 4.2.27 on 2026-01-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OPDStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("department", models.CharField(max_length=100)),
                ("total_patients", models.IntegerField(default=0)),
                (
                    "average_wait_time",
                    models.FloatField(
                        default=0, help_text="Average wait time in minutes"
                    ),
                ),
                (
                    "average_consultation_time",
                    models.FloatField(
                        default=0, help_text="Average consultation time in minutes"
                    ),
                ),
                (
                    "peak_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="Hour with maximum patients (0-23)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "department")},
            },
        ),
        migrations.CreateModel(
            name="OPDQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_number", models.IntegerField()),
                ("department", models.CharField(max_length=100)),
                ("doctor_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_wait_time",
                    models.IntegerField(
                        default=0, help_text="Estimated wait time in minutes"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opd_visits",
                        to="authentication.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "check_in_time"],
            },
        ),
    ]
