# Generated by Django 4.2.27 on 2026-01-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OPDQueue",
        ),
    ]
