# Generated by Django 4.2.27 on 2026-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "condition",
                    models.TextField(help_text="Rule condition in JSON format"),
                ),
                (
                    "recommended_bed_type",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("ICU", "ICU"),
                            ("Ventilator", "Ventilator"),
                            ("Emergency", "Emergency"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recommended_department", models.CharField(max_length=100)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
    ]
